name: React App Deployment on Surge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        run: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Node Dependencies
        run: npm i
      - name: Build React App
        run: npm run build
      - name: Deploy on Surge
        run: surge ./ base-app-zeeforumcompany.surge.sh --token ${{ secrets.SURGE_TOKEN }}